# This is a basic workflow to help you get started with Actions

name: Hello oca

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use hello-oca customize docker action
      - name: Hello oca members
        uses: ./.github/actions/hello-oca
        with:
          member1: "Nuri Bang"
          member2: "Justin Yoo"